### PR TITLE
RFC: Run webserver and websocket server under twistd

### PR DESCRIPTION
**Pull request by pao**
Addresses #12.

`twistd -noy cah.tac` for development; `twistd -y cah.tac` daemonizes.

Note there's still configuration stuff not properly factored out in the .tac file, but this is now workable.

### CODE REVIEW

**Comment by pao** [comment]
This basically works now. Configuration needs to be factored out properly. I'll get to it tomorrow.

**Comment by berrycardsagainsthumanity** [comment]
I was trying to run a server on a different port and I noticed that the cah.js has some values that need to be read from the config as well. (The websocket port number and wamp namespace)

Maybe move them to the init.js and have init.js templated in?

**Comment by pao** [comment]
Configuration of server/port should be fully factored out into config.yml now.

Now requires `pystache` to template the JS.

I've carefully arranged so `init.js` is the only file that gets the templating treatment.

**Comment by pao** [comment]
This should be good to merge, BTW. Review on!

**Pull request merged**
