### PR TITLE
Compliance with CAH terms of use

### PR DESCRIPTION
**Pull request by pao**
Adds required notices for use of original CAH content, and removes the
string "Cards Against Humanity", which is reserved for the original game.

### CODE REVIEW

**Comment by pao** [comment]
This partially addresses #6, BTW.

**Comment by berrycardsagainsthumanity** [comment]
Merged this in, cleaned up the styling to it pops up as a dialog and then added target="_blank" to the external links so it doesn't navigate anyone away accidentally!

**Comment by pao** [comment]
I don't see these changes on `master`.

**Comment by pao** [comment]
There's the push.

**Comment by berrycardsagainsthumanity** [comment]
Yeah, looks like I committed last night but forgot to push. It was getting pretty late. :)

**Pull request closed without merging**
